name: CI

on: [push]

jobs:
  lint:
    name: Codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 3.5
      - name: Regenerate docs
        shell: bash
        run: |
          ./.panvimdoc/panvimdoc.sh
      - name: Check that docs are up-to-date
        run: git diff --exit-code -- doc/jupytext.txt
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: v0.10.2
      - name: Install Jupytext
        run: |
          python -m pip install --upgrade pip
          pip install jupytext
      - name: Run test
        shell: bash
        run: |
          ./run_tests.sh
